name: Release Scheduler CI
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  releaseScheduler:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Run release-scheduler
        uses: koj-co/release-scheduler@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
